{{- range .Values.workers }}
---
# Driver ConfigMap per worker
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-{{ .name }}-driver-config
data:
  driver-config.yaml: |
{{ toYaml .driverConfig | indent 4 }}

{{- end }}