apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker-sa
  namespace: oxia-bench
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sts-reader
  namespace: oxia-bench
rules:
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: worker-sts-reader
  namespace: oxia-bench
subjects:
  - kind: ServiceAccount
    name: worker-sa
    namespace: oxia-bench
roleRef:
  kind: Role
  name: sts-reader
  apiGroup: rbac.authorization.k8s.io